"use server"

import crypto from "node:crypto"
import { rememberUserRecipe } from "@/lib/server/recipe-store"
import { createClient } from "@/lib/supabase/server"
import type { RecipeGenerationResult, RecipeDetailView } from "@/lib/types/recipetypes"
import { resolvePantryRequestUrl } from "@/lib/utils/config"
import { RECIPES_GENERATE_PATH } from "@/lib/types/recipetypes"

/**
 * Server Action to prompt Chef ACE backend to generate a recipe.
 * Automatically persists the generated recipe to the database/cache so it
 * can be resolved when the user redirects to the recipe detail view.
 */
export async function generateRecipeWithAI(
    accessToken: string,
    userInstruction: string,
): Promise<RecipeDetailView> {
    const url = resolvePantryRequestUrl(RECIPES_GENERATE_PATH)

    // Pass the user's instruction directly as the pantry_items query parameter.
    // The backend vector store will perform a similarity search on the pantry_items
    // table to retrieve the most semantically relevant ingredients.
    const payload = {
        pantry_items: [userInstruction.trim()],
        dietary_preferences: [],
    }

    const res = await fetch(url, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify(payload),
    })

    if (!res.ok) {
        if (res.status === 429) {
            throw new Error("Rate limit exceeded. Try again in a minute.")
        }
        throw new Error(
            "Chef ACE is temporarily unable to generate a recipe. Please try again shortly."
        )
    }

    const result = (await res.json()) as RecipeGenerationResult
    const recipe = result.recipe
    console.log("[rag-recipe] Generated recipe:", recipe)
    const cleanedData: RecipeDetailView = {
        id: crypto.randomUUID(),
        title: recipe.title ?? "AI Suggested Recipe",
        ingredients: recipe.ingredients ?? [],
        instructions: recipe.instructions ?? [],
        source: "generated",
        subtitle: "Generated by Chef ACE",
        description: `AI-generated recipe formulated based on: "${userInstruction}"`,
        category: "AI Chef",
        tags: ["chef-ace", "ai-generated"],
        retrieved_context: result.retrieved_context ?? [],
    }

    // Persist the generated recipe under user's remembered recipes
    try {
        const supabase = await createClient()
        const {
            data: { user },
        } = await supabase.auth.getUser()
        if (user?.id) {
            await rememberUserRecipe(user.id, cleanedData)
        }
    } catch (err) {
        console.warn("[rag-recipe] Could not persist generated recipe to cache:", err)
    }

    return cleanedData
}