import type {
  MealDbRandomRecipe,
  RecipeDetailView,
  RecipeGenerationResult,
} from "@/lib/types/recipetypes"
import type { DummyRecipe } from "@/lib/data/dummy-recipes"

export function toRecipeDetailFromDummy(recipe: DummyRecipe): RecipeDetailView {
  return {
    id: recipe.id,
    title: recipe.title,
    description: recipe.description,
    ingredients: recipe.ingredients,
    instructions: recipe.instructions,
    source: "dummy",
    subtitle: recipe.subtitle,
    category: recipe.category,
    tags: recipe.tags,
  }
}

export function toRecipeDetailFromMealDb(recipe: MealDbRandomRecipe): RecipeDetailView {
  return {
    id: recipe.id,
    title: recipe.title,
    ingredients: recipe.ingredients,
    instructions: recipe.instructions,
    source: "mealdb",
    subtitle: "Chef ACE · TheMealDB",
    category: recipe.category,
    tags: recipe.tags,
  }
}

export function toRecipeDetailFromGenerated(
  id: string,
  result: RecipeGenerationResult,
): RecipeDetailView {
  return {
    id,
    title: result.recipe.title,
    ingredients: result.recipe.ingredients,
    instructions: result.recipe.instructions,
    source: "generated",
    subtitle: "Generated by Chef ACE from your pantry",
    retrieved_context: result.retrieved_context,
  }
}

export function formatCategoryLabel(category: string | undefined): string {
  if (!category) return "Recipe"
  return category.charAt(0).toUpperCase() + category.slice(1)
}

export function sourceBadgeLabel(source: RecipeDetailView["source"]): string {
  if (source === "dummy") return "Sample"
  if (source === "mealdb") return "TheMealDB"
  return "AI generated"
}
